spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
              - profile
              - email
